question_repo/apps/accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

# CBV => class base view
# FBV => function base view

urlpatterns = [
    # 注册
    url(r'register/$', views.Register.as_view(), name="register"),
    # 登录
    url(r'^login/$', views.Login.as_view(), name='login'),
    # 退出
    url(r'logout/$', views.logout, name="logout"),
    # 忘记密码
    url(r'password/forget/$', views.test, name="password_forget"),
    # 重置密码
    url(r'password/reset/token/$',views.test, name="password_reset"),
]

question_repo/apps/apis/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^mobile_captcha/$', views.get_mobile_captcha, name="mobile_captcha"),
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    url(r'^check_captcha/$', views.check_captcha, name='check_captcha'),
    url(r'^questions/$', views.QuestionsView.as_view(), name='questions'),
    url(r'^question/collection/(?P<id>\d+)/$', views.QuestionCollectionView.as_view(), name='question_collection'),
    url(r'^answer/(?P<id>\d+)/$', views.AnswerView.as_view(), name="answer"),
    # url(r'^answer/(?P<id>\d+)/$', views.AnswerView.as_view(), name="answer"),
    url(r'^other_answer/(?P<id>\d+)/$', views.OtherAnswerView.as_view(), name="other_answer"),
    url(r'^answer/collection/(?P<id>\d+)/$', views.AnswerCollectionView.as_view(), name='answer_collection'),
]

question_repo/apps/repo/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^$', views.index, name='index'),

    # 题目列表
    url(r'^questions/$', TemplateView.as_view(template_name="questions.html"), name="questions"),
    # 贡献题目
    url(r'^question/$', views.questions, name="question"),
    # 题目详情，捕获了一个参数
    url(r'^question/(?P<id>\d+)/$',views.QuestionDetail.as_view(), name="question_detail"),

]

question_repo/question_repo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logtest/$', views.logtest, name="logtest"),
    url(r'^accounts/', include('apps.accounts.urls', namespace="accounts")),
    url(r'^apis/', include('apps.apis.urls', namespace="apis")),
    url(r'^uc/', include('apps.usercenter.urls', namespace="uc")),
    url(r'^', include('apps.repo.urls', namespace="repo")),
    url(r'^media/(?P<path>.*)$',  serve, {"document_root": MEDIA_ROOT}),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

question_repo/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import check_password as auth_check_password
from .models import User


# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="密 码2", widget=widgets.PasswordInput(attrs={"class":"form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(attrs={"style":"width: 160px;padding: 10px", "placeholder":"验证码", "error_messages": {"invalid": "验证码错误"}}))
    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
            'mobile': widgets.TextInput(attrs={"class":"form-control", "placeholder": "请输入手机号"}),
            'password': widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username
    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")


# 用户登录表单
# 因为是登录功能，所以不适合ModelForm。
# ModelForm对于unique字段会检查是否已经存在，如果存在，is_valid结果会为False
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
                               widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"}}))
    password = forms.CharField(label="密 码",
                               widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

    def clean_username(self):
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名或密码不正确")

question_repo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html style="overflow: hidden;" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/img/favicon.html">
    <title>{% block title %}BASE{% endblock %}-题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    {% block load_css %}
    {% endblock %}
    <style>
      body{
          font-size: 14px; !important;
      }
    </style>
</head>
<body>
    <div class="container">
        <section id="container" class="">
          <!--header start-->
          <header class="header white-bg">
              <!--logo start-->
              <a href="#" class="logo">三创<span>题库</span></a>
              <!--logo end-->
              <div class="top-nav">
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <ul class="nav navbar-nav">
                    <li class="active">
                      <a class="" href="http://127.0.0.1:8000/">
                          <span> 首页 </span>
                      </a>
                    </li>
                    <li class="">
                        <a class="" href="http://127.0.0.1:8000/question/">
                      <span> 校招题 </span>
                    </a>
                    </li>
                  </ul>
                  <ul class="nav pull-right top-menu">
                      <li>
                          <form action="{% url 'repo:question' %}">
                             <input type="text" class="form-control search" placeholder="Search" name="search" id="search" value="{{ search_key }}">

                          </form>
                      </li>
                      <!-- user login dropdown start-->

                      <li class="dropdown">
                          <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                              <img alt="" src="{% static 'img/1534323246.png' %}" height="30px">

                              <span class="username">admin</span>
                              <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                              <div class="log-arrow-up"></div>
                              <li><a class="" href="http://127.0.0.1:8000/uc/profile/"> 个人资料 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/change_passwd/"> 修改密码 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/answer/"> 我的回答 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/collect/"> 我的收藏 </a></li>
                              <li><a class="" href="#myModal-1" data-toggle="modal"> 贡献题目 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/uc/contribut/"> 我的贡献 </a></li>
                              <li><a class="" href="http://127.0.0.1:8000/accounts/logout/"> 退出 </a></li>
                          </ul>
                      </li>

                      <!-- user login dropdown end -->
                  </ul>
              </div>
          </header>
          <!--header end-->
          <!--main content start-->
          <section id="main-content">
              <section class="wrapper">
                <!-- page start-->
                <div class="row">
                    {% block content %}这是BASE页面{% endblock %}
                </div>
                <!-- page end-->
              </section>
          </section>
          <!--main content end-->
          </section>
    </div>
    {% include 'crontribute_modal.html' %}
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <!--common script for all pages-->
    <script src="{% static 'js/common-scripts.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}" ></script>
    {% block load_js %}
    {% endblock %}
    <script>
      //owl carousel
      $(document).ready(function() {
          $("#owl-demo").owlCarousel({
              navigation : true,
              slideSpeed : 300,
              paginationSpeed : 400,
              singleItem : true
          });
      });
    </script>
</body>
</html>

question_repo/templates/crontribute_modal.html
{# My Modal 模态框 #}
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal-1" class="modal fade">
<div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 class="modal-title">贡献题目</h4>
      </div>
      <div class="modal-body">
          <form class="form-horizontal" role="form" method="post" action="/question/">
              <div class="form-group">
                  <label for="inputQuestionTitle" class="col-lg-2 control-label">标题</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" id="inputQuestionTitle" name="title" placeholder="标题">
                  </div>
              </div>
               <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">分类</label>
                    <div class="col-lg-10">
                        <select class="form-control" id="分类" name="category">
                            <option value="0"> 选择分类 </option>
                                <option value="{{ item.id }}">{{ item.name }}</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">内容</label>
                    <div class="col-lg-10">
                        <textarea type="text" class="form-control" id="inputQuestionTitle" name="content" placeholder="内容"></textarea>
                    </div>
                </div>
              <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                      <button type="submit" class="btn btn-default">提交</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
</div>

question_repo/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户登录-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
          <form class="form-signin" method="post">
            {% csrf_token %}
            <h2 class="form-signin-heading">登录</h2>
            <div class="login-wrap">
{#                {{ request.user }}#}
{#                {{ DEFAULT_MESSAGE_LEVELS }}#}
                {{ form.username}}
                {{ form.password}}
                {{ form.captcha}}
                <a href="javascript:void(0);"><img id="captcha_img" src="#" ></a>
                <div class="user-reg">
                    <a href="{% url 'accounts:register' %}"> 用户注册</a>
                    <span class="pull-right"> <a href=""> 忘记密码?</a></span>
                </div>
                <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
                <p class="msg"></p>
            </div>
          </form>
        </div>
    <script>
    get_captcha_img();
    $("#captcha_img").click(get_captcha_img);

    function get_captcha_img() {
        $.ajax({
            url: '{% url 'apis:get_captcha' %}',
            type: 'GET',
            dataType: 'text',
            success: function (data) {
                $('#captcha_img').attr('src', data);
            }
        });
    }

        // 这里在form中定义了，如果没定义可以用jquery添加事件
    // $("#id_captcha").blur(check_captcha);

    // 当失去焦点时检查验证码
    function check_captcha() {
        var captcha_code = $('#id_captcha').val();
        if (captcha_code.length == 0){
            return false
        }
        $.ajax({
            url: '{% url 'apis:check_captcha' %}',
            type: 'GET',
            dataType: 'json',
            data: {"captcha_code": captcha_code},
            success: function (data) {
                if(data.code == 400){
                     $('.msg').html("验证码错误");
                }else{
                    $('.msg').html("");
                }
            }
        });
    };
    </script>
    </body>
</html>

question_repo/templates/question.html
{% extends 'base.html' %}
  {% load staticfiles %}
  {% block content %}
  <div class="row">
      <div class="col-md-9">
          <!--刷题汇报 start-->
          <section class="panel">
            <div class="revenue-head">
                <span>
                    <i class="icon-bar-chart"></i>
                </span>
                <h3>刷题汇报</h3>
            </div>
            <div class="panel-body">
                <div class="row">


              <div id="toolbar_table_questions">
                  <form class="form-inline" role="form">
                      <div class="form-group">
                          <select class="form-control" id="grade" name="grade">
                              <option value="0"> 选择难度 </option>
                              {% for item in grades %}
                              <option value="{{ item.0 }}"> {{ item.1 }} </option>
                              {% endfor %}
                          </select>
                      </div>
                      <div class="form-group">
                          <select class="form-control" id="category" name="category">
                              <option value="0"> 选择分类 </option>
                              {% for item in category %}
                              <option value="{{ item.id }}">{{ item.name }}</option>
                              {% endfor %}
                          </select>
                      </div>
                      <div class="form-group">
                          <select class="form-control" id="status" name="status">
                              <option value="2"> 选择状态 </option>
                              <option value="0"> 待刷 </option>
                              <option value="1"> 已刷 </option>
                          </select>
                      </div>
                  </form>
              </div>

                      <table id="table_questions" name="table_questions"
                             data-toolbar="#toolbar_table_questions"
                             data-query-params="queryParams"
                          data-toggle="table"
                          data-unique-id="id"
                          data-id-table="advancedTable"
                          {# 分页方式：服务端、客户端分页 #}
                          data-side-pagination="server"
                          {# data-toolbar="#toolbar_table_questions" #}
                          data-show-columns="true"
                          data-page-list="[10, 25, 50, 100, ALL]"
                          data-pagination="true"
                          data-page-size="25"
                          data-pagination-first-text="首页"
                          data-pagination-pre-text="上一页"
                          data-pagination-next-text="下一页"
                          data-pagination-last-text="末页"
                          data-show-refresh="true"
                          {#data-query-params="queryParams"#}
                          data-url="/apis/questions"
                          data-show-export="true"
                          data-export-types="['excel']"
                          data-export-options='{
                          "fileName": "三创题库",
                          "worksheetName": "所有习题",
                          }'>
                                                   <thead>
        <tr>
          <th data-field="state" data-checkbox="true"></th>
          <th data-field="id">序号</th>
          <th data-field="title"
              data-formatter="titleFormatter">标题</th>
          <th data-field="grade"
              data-formatter="gradeFormatter"
          >难度</th>
          <th data-field="answer"
              data-formatter="answerFormatter"
          >答题率</th>
          <th data-field="oper"

              data-formatter="operateFormatter"

              data-events="operateEvents"
          >操作</th>
        </tr>
  </thead>
                   </table>
                </div>
            </div>
          </section>
          <!--revenue end-->
      </div>
      <div class="col-md-3">
          {% include 'right.html' %}
      </div>
  </div>
  {% endblock %}
{% block load_js %}
      <script src="{% static 'assets/bootstrap-table/bootstrap-table.js' %}"></script>
      <script src="{% static 'assets/bootstrap-table/locale/bootstrap-table-zh-CN.min.js' %}"></script>
      <script src="{% static 'assets/bootstrap-table/tableExport.js' %}"></script>
      <script src="{% static 'assets/bootstrap-table/extensions/export/bootstrap-table-export.js' %}"></script>
    <script>
    function queryParams(tableParams) {

           var params = {};
      // 每页多少条数据
      params['limit'] = tableParams.limit;
      // 偏移量
      params['offset'] = tableParams.offset;
      // 当前第几页
      params['page'] = $table.bootstrapTable('getOptions').pageNumber;
      params['search'] = $('#search').val();
      // 工具栏上所有select
      $("#toolbar_table_questions").find("select[name]").each(
          function () {
              params[$(this).attr('name')] = $(this).val();
          }
      );
      return params
      }

      // 当修改查询参数时，重新加载table数据
      // 获取Table
      var $table = $('#table_questions');
      var $select_grade = $('#grade');
      var $select_category = $('#category');
      var $select_status = $('#status');

      $(function () {
          // 切换难度
          $select_grade.change(function () {
              $table.bootstrapTable('refresh');
          });
          // 切换分类
          $select_category.change(function () {
              $table.bootstrapTable('refresh');
          });
          // 切换状态
          $select_status.change(function () {
              $table.bootstrapTable('refresh');
          });
      });
      function gradeFormatter(value, row, index) {
       // value => 该单元格数据
       // row =>   该行数据
       // index => 数据在当前页的索引（从0开始）
       console.log(value);
       console.log(row);
       console.log(index);
       html = '<span class="label label-default">未知</span>';
      if (value == 1){
          html = '<span class="label label-info">入门</span>'
      }else if(value == 2){
          html = '<span class="label label-info">简单</span>'
      }else if(value == 3) {
          html = '<span class="label label-success">一般</span>'
      }else if(value == 4){
          html = '<span class="label label-danger">困难</span>'
      }else if(value == 5) {
          html = '<span class="label label-danger">超难</span>'
      }
      return html
   }
   function titleFormatter(value, row, index) {
  {#          url_question_detail = "/question/"+row.id+"/"; #}
      url_question_detail = "{% url 'repo:question_detail' '0000' %}";
      url_question_detail = url_question_detail.replace('0000', row.id);
      // 返回标题的前50个字符
      return "<a href='"+url_question_detail+"'>"+row.title.substring(0, 50)+"</a>";
   }

   // 定义答题率格式，返回html字符串
   function answerFormatter(value, row, index) {
      return '17%'
  }
   function operateFormatter(value, row, index) {
        if(row.collection == true){
            li = '<i class="glyphicon glyphicon-heart question-id-'+row.id+'"></i>'
        }else{
            li = '<i class="glyphicon glyphicon-heart-empty question-id-'+row.id+'"></i>'
        }
        return [
            '<a class="like" href="javascript:void(0)" title="收藏">',
            li,
            '</a>',
        ].join('');
  }
   operateEvents = {
      // 操作栏，like按钮
      'click .like': function (e, value, row) {
          // alert('You click like action, row: ' + JSON.stringify(row));
          // ajax调用接口：'/apis/question/collection/'+ row.id +'/'
          $.ajax({
              url: '/apis/question/collection/'+ row.id +'/',
              type: 'GET',
              // dataType: 'json',
              success: function (data) {
                  if(data.code == 200){
                      obj_a = $(".question-id-"+row.id);
                      // 根据状态显示爱心
                      if(data.msg.status){
                          obj_a.attr("class", "glyphicon glyphicon-heart "+"question-id-"+row.id)
                      }else{
                          obj_a.attr("class", "glyphicon glyphicon-heart-empty "+"question-id-"+row.id)
                      }
                  }
              },
              error: function () {
                  alert('error');
              }
          });
      },
  };
      </script>

  {% endblock %}

  {% block load_css %}
  <link rel="stylesheet" href="{% static 'assets/bootstrap-table/bootstrap-table.css' %}">
  {% endblock %}

question_repo/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户注册-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
    {# 加载提示工具对应的js和css #}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
            <form class="form-signin" id="register_form">
              {% csrf_token %}
              <h2 class="form-signin-heading">用户注册</h2>
              <div class="login-wrap">
                  {{ form.username }}
                  {{ form.password }}
                  {{ form.password2 }}
                  {{ form.mobile }}
                  {{ form.mobile_captcha }}
                  {# 给发送短信按钮添加动作 #}
                  <input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/>
                  <button class="btn btn-lg btn-login btn-block" type="button" id="register_btn">注册</button>
                  <label class="checkbox">
                      <span class="pull-right"> 已有帐号， <a href="{% url 'accounts:login' %}"> 请登录 </a></span>
                  </label>
                  <div class="alert alert-block alert-danger fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        <strong>提醒!</strong> 错误提示信息~~
                  </div>
              </div>
            </form>
        </div>
    {# 添加js动作#}
    <script>
        {# 发送短信验证码 #}
        function sendmessage(obj,second){
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if(telRegex.test($.trim($("#id_mobile").val()))){
                $.ajax({
                    url: "{% url 'apis:mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#id_mobile").val()},
                    success: function (data) {
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: data.msg
                        });
                    }
                });
                countDown(obj,second)
            } else{
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: '提交结果',
                    // (string | mandatory) the text inside the notification
                    //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj,second){
        // 如果秒数还是大于0，则表示倒计时还没结束
         if(second>=0){
              // 获取默认按钮上的文字
              if(typeof buttonDefaultValue === 'undefined' ){
                buttonDefaultValue =  obj.defaultValue;
            }
            // 按钮置为不可点击状态
            obj.disabled = true;
            // 按钮里的内容呈现倒计时状态
            obj.value = buttonDefaultValue+'('+second+')';
            // 时间减一
            second--;
            // 一秒后重复执行
            setTimeout(function(){countDown(obj,second);},1000);
            // 否则，按钮重置为初始状态
            }else{
            // 按钮置未可点击状态
            obj.disabled = false;
            // 按钮里的内容恢复初始状态
            obj.value = buttonDefaultValue;
           }
        }
    $("#register_btn").click(function () {
          // some_check
          $.ajax({
              url: "{% url 'accounts:register' %}",
              type: "POST",
              dataType: "json",
              data: $("#register_form").serialize(), // {"username":'cali'}
              success: function (data) {
                  if(data.status == 200 ){
                      window.location.href='{% url 'repo:index' %}';
                  }else{
                      msg = "新错误类型";
                      if(data.status == 400 || data.status == 401){
                          msg = data.msg
                      }else{
                          // 402 => form.errors
                          for(var i in data.msg){
                              msg = i+data.msg[i];
                              break
                          }
                      }
                       $.gritter.add({
                          // (string | mandatory) the heading of the notification
                          title: '提交结果',
                          // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                          text: msg
                      });
                   }
              },
              // 解决csrftoken
              beforeSend: function(xhr, settings) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
              }
          });
      });
    </script>

    </body>
</html>